#!/sbin/sh

# start aroma bootmenu
source /sbin/bootrec-device
busybox mount -t yaffs2 $BOOTREC_CACHE /cache
busybox mkdir /sdcard
busybox mount -o errors=remount-ro /dev/block/mmcblk0p1 /sdcard
busybox mkdir /turbo
busybox mount -o bind,errors=remount-ro /sdcard/turbo /turbo
busybox rm /tmp/bootrec
busybox mkdir /tmp
busybox echo 0 > $BOOTREC_LED_RED
busybox echo 0 > $BOOTREC_LED_GREEN
busybox echo 0 > $BOOTREC_LED_BLUE
/sbin/aroma 1 0 "/sbin/aroma-res.zip"
# copy repair log to sdcard if requested
if [ -e /tmp/turbo_repair.ready2copy ]; then
    busybox rm /tmp/turbo_repair.ready2copy
    busybox mv /tmp/turbo_repair.log /sdcard/turbo_repair.log
fi
busybox sync
if [ -e /tmp/bootrec ]; then
    source /tmp/recslot
    busybox cp -f $FSTAB /etc/recovery.fstab
    if [ -e /res/ui.xml ]; then
        # add current slot # to TWRP header
        sed -i 's/<text>Current Slot -.*<\/text>/<text>Current Slot - '$CURRENTSLOT'<\/text>/g' /res/ui.xml
    fi
    /sbin/recovery
fi
busybox sync
busybox umount -l /dev/block/mmcblk0p1
busybox umount -l /dev/block/mmcblk0p2
reboot
