#!/sbin/busybox sh
#
echo "Unmounting /system..."
umount -f /system
echo "Unmounting /data..."
umount -f /data
echo "Unmounting /dev/block/mmcblk0p1..."
umount -f /dev/block/mmcblk0p1
echo "Restarting..."
/sbin/reboot
